# Generated by Django 4.0.5 on 2022-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortener',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
